---
 - shell: "curl -sL https://deb.nodesource.com/setup_7.x | bash -"
   become: yes
 - apt: name={{ item }} state="latest"
   become: yes
   with_items:
     - nodejs
     - build-essential
 - file: path=~/.npm-global state=directory
 - shell: npm config set registry 'http://registry.npmjs.org'
 - shell: npm config set prefix '{{ ansible_env.HOME }}/.npm-global'
 - shell: npm install -g {{ item }}
   with_items:
     - npm
     - yarn
 - command: "yarn global add {{ item }} "
   with_items:
     - gulp
     - yo
     - bower
     - eslint
