---
 - shell: yaourt -S --noconfirm --needed nodejs npm
 - file: path=~/.npm-global state=directory
 - shell: npm config set registry 'http://registry.npmjs.org'
 - shell: npm config set prefix '~/.npm-global'
 - shell: npm config set progress false
 - shell: npm install -g {{ item }}
   with_items:
     - npm
     - npm-proxy-cache
 - shell: npm config set proxy http://localhost:8080/ && npm config set https-proxy http://localhost:8080/ && npm config set strict-ssl false
 - npm: name={{ item }} state=latest global=yes
   with_items:
     - gulp
     - npm-cache
     - yo
     - bitbucket-cli
     - bower
