---
 - apt: name={{ item }} state="latest"
   become: yes
   with_items:
     - nodejs-legacy
     - npm
 - file: path=~/.npm-global state=directory
 - shell: npm config set registry 'http://registry.npmjs.org'
 - shell: npm config set prefix '~/.npm-global'
 - shell: npm install -g {{ item }}
   with_items:
     - npm
     - npm-proxy-cache
 - npm: name={{ item }} state=latest global=yes
   with_items:
     - gulp
     - npm-cache
     - yo
     - bitbucket-cli
     - bower
